clickhouse-mate: [clickhouse-mate/**]
cloud-controller-manager-azure: [cloud-controller-manager-azure/**]
cloud-controller-manager-gcp: [cloud-controller-manager-gcp/**]
cloud-controller-manager-hcloud: [cloud-controller-manager-hcloud/**]
cloud-controller-manager-oci: [cloud-controller-manager-oci/**]
cloud-controller-manager-openstack: [cloud-controller-manager-openstack/**]
cloud-controller-manager-scaleway: [cloud-controller-manager-scaleway/**]
cluster-autoscaler: [cluster-autoscaler/**]
contolplane-lb: [contolplane-lb/**]
csi-oci: [csi-oci/**]
curl: [curl/**]
deckschrubber: [deckschrubber/**]
fluentd: [fluentd/**]
git-chglog: [git-chglog/**]
github-actions-runner: [github-actions-runner/**]
haproxy: [haproxy/**]
helm: [helm/**]
ipsec: [ipsec/**]
keydb: [keydb/**]
mongodb: [mongodb/**]
mongosqld: [mongosqld/**]
mongosync: [mongosync/**]
nginx-openresty: [nginx-openresty/**]
openvpn: [openvpn/**]
pgbadger: [pgbadger/**]
pgbouncer: [pgbouncer/**]
postgresql: [postgresql/**]
pvc-autoresizer: [pvc-autoresizer/**]
renovate: [renovate/**]
reviewdog: [reviewdog/**]
skipper: [skipper/**]
skopeo: [skopeo/**]
supercronic: [supercronic/**]
tabix: [tabix/**]
teamcity: [teamcity/**]
tinyproxy: [tinyproxy/**]
vals: [vals/**]
wal-g: [wal-g/**]
wireguard: [wireguard/**]
ytt: [ytt/**]
